# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  Solution: 'UWPX-Client.sln'
  BuildConfiguration: 'Debug'
  BuildPlatform: 'ARM'
  AppxPackageDir: '$(Build.artifactStagingDirectory)\AppxPackages\\'
  ArtifactName: 'UWPX-$(BuildPlatform)-$(BuildConfiguration)'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  displayName: 'NuGet Restore'
  inputs:
    restoreSolution: '$(Solution)'

- task: DownloadSecureFile@1
  name: 'signingCert'
  displayName: 'Download Signing Certificate'
  inputs:
    secureFile: 'UWPX_UI_TemporaryKey.pfx'

- task: VSBuild@1
  displayName: 'Build $(BuildPlatform) Debug'
  inputs:
    solution: '$(Solution)'
    vsVersion: '16.0'
    msbuildArgs: '/p:AppxBundlePlatforms="$(BuildPlatform)"
                  /p:AppxPackageDir="$(AppxPackageDir)"
                  /p:AppxBundle=Always
                  /p:UapAppxPackageBuildMode=StoreUpload
                  /p:AppxPackageSigningEnabled=true
                  /p:PackageCertificateThumbprint="" 
                  /p:PackageCertificateKeyFile="$(signingCert.secureFilePath)"
                  /t:Packaging'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: PowerShell@2
  displayName: 'Install PFX file'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Start adding the PFX file to the certificate store."

      $pfxpath = '$(signingCert.secureFilePath)'
      
      Add-Type -AssemblyName System.Security
      $cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2
      $cert.Import($pfxpath, "", [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]"PersistKeySet")
      $store = new-object system.security.cryptography.X509Certificates.X509Store -argumentlist "MY", CurrentUser
      $store.Open([System.Security.Cryptography.X509Certificates.OpenFlags]"ReadWrite")
      $store.Add($cert)
      $store.Close()

# Does not discover any tests:
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**\*_$(BuildPlatform)_$(BuildConfiguration).appxbundle'
    searchFolder: '$(AppxPackageDir)'
    otherConsoleOptions: '/Logger:trx'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(ArtifactName)'
